- src/main/kotlin/no/fdk/fdk_reasoning_service/config/MongoConf.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/config/MongoDatabases.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/rdf/ModellDCATAPNO.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/repository/InformationModelRepository.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/InfoModelService.kt
- src/main/resources/application.yml
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/InformationModels.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/utils/TestData.kt
- src/test/resources/infomodel_0.ttl
- src/test/resources/infomodels.ttl
resolve #14 (information model)
> feat: persist reasoned information models

- pom.xml
- src/main/kotlin/no/fdk/fdk_reasoning_service/controller/ConceptsController.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/controller/DataServiceController.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/controller/DatasetsController.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/controller/EventsController.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/controller/InformationModelsController.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/controller/PublicServicesController.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/controller/Utils.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/repository/InformationModelRepository.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/ConceptService.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/DataServiceService.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/DatasetService.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/EventService.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/InfoModelService.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/PublicServiceService.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/Utils.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/integration/ConceptsIntegration.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/integration/DataServicesIntegration.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/integration/DatasetsIntegration.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/integration/EventsIntegration.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/integration/InformationModelsIntegration.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/integration/PublicServicesIntegration.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/InformationModels.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/utils/ApiTestContext.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/utils/DatabaseData.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/utils/TestData.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/utils/TestResponseReader.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/utils/TestUtils.kt
Stig vil avvente spørsmålet på om vi skal ha en egen tjeneste for henting av rdf-data, så i første omgang får reasoning service endepunktene
resolve #15
> feat: get reasoned rdf-data

- .github/workflows/deploy-staging.yaml
> feat: add staging deploy

- .github/workflows/deploy-demo.yaml
- .github/workflows/deploy-prod.yaml
- pom.xml
- src/main/kotlin/no/fdk/fdk_reasoning_service/Application.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/rabbit/RabbitMQConfig.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/rabbit/RabbitMQListener.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/rabbit/RabbitMQPublisher.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/ReasoningActivity.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/Utils.kt
- src/main/resources/application.yml
> feat: add rabbit listener & publisher

- src/main/kotlin/no/fdk/fdk_reasoning_service/rdf/PROV.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/ReasoningService.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/Rules.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/Utils.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/Concepts.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/InformationModels.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/utils/ResponseMock.kt
- src/test/resources/concept_0.ttl
- src/test/resources/concepts.ttl
- src/test/resources/dataservice_0.ttl
- src/test/resources/dataset_0.ttl
- src/test/resources/datasets.ttl
- src/test/resources/event_0.ttl
- src/test/resources/fdk_ready_concepts.ttl
- src/test/resources/fdk_ready_dataservices.ttl
- src/test/resources/fdk_ready_datasets.ttl
- src/test/resources/fdk_ready_events.ttl
- src/test/resources/fdk_ready_infomodels.ttl
- src/test/resources/fdk_ready_public_services.ttl
- src/test/resources/infomodel_0.ttl
- src/test/resources/infomodels.ttl
- src/test/resources/org.ttl
- src/test/resources/orgs.ttl
- src/test/resources/public_service_0.ttl
> Extend org resources

- src/main/kotlin/no/fdk/fdk_reasoning_service/service/ReasoningService.kt
- src/test/resources/events.ttl
- src/test/resources/fdk_ready_concepts.ttl
- src/test/resources/fdk_ready_events.ttl
> fix: add name for publishers missing foaf:name

- src/main/kotlin/no/fdk/fdk_reasoning_service/service/ReasoningService.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/Utils.kt
- src/test/resources/datasets.ttl
- src/test/resources/fdk_ready_datasets.ttl
> fix: add orgPath for blank node publishers

- src/main/kotlin/no/fdk/fdk_reasoning_service/service/ReasoningActivity.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/ReasoningService.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/Concepts.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/DataServices.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/Datasets.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/Events.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/InformationModels.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/PublicServices.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/Reasoning.kt
> fix: abort reasoning process when missing org or los data

- src/main/kotlin/no/fdk/fdk_reasoning_service/model/StartAndEnd.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/model/StartAndEndTime.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/rabbit/RabbitMQPublisher.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/ReasoningActivity.kt
> chore: rabbit messages contains start & end datetimes

- src/main/kotlin/no/fdk/fdk_reasoning_service/service/ConceptService.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/DataServiceService.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/DatasetService.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/InfoModelService.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/Utils.kt
> fix: rm resources with incorrect type from catalog lists

- pom.xml
- src/main/kotlin/no/fdk/fdk_reasoning_service/rdf/CV.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/ReasoningService.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/Utils.kt
- src/test/resources/fdk_ready_public_service_0.ttl
- src/test/resources/fdk_ready_public_services.ttl
- src/test/resources/public_service_0.ttl
> extend service actors from property cv:ownedBy with org-cat data

- src/main/kotlin/no/fdk/fdk_reasoning_service/rdf/DCAT3.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/DatasetService.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/Rules.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/Datasets.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/Reasoning.kt
- src/test/resources/dataset_series.ttl
- src/test/resources/fdk_ready_dataset_series.ttl
> feat: add support for dcat:DatasetSeries

- docker-compose.yaml
- src/main/kotlin/no/fdk/fdk_reasoning_service/model/Reports.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/rabbit/RabbitMQListener.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/ReasoningActivity.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/Retry.kt
> feat: retry reasoning

- src/main/kotlin/no/fdk/fdk_reasoning_service/controller/EventsController.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/rdf/DCATNO.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/EventService.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/integration/EventsIntegration.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/Events.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/Reasoning.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/utils/DatabaseData.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/utils/TestData.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/utils/TestUtils.kt
- src/test/resources/events.ttl
- src/test/resources/fdk_ready_event_1.ttl
- src/test/resources/fdk_ready_event_catalogs.ttl
> chore: handle event catalogs

- src/main/resources/application.yml
> fix: set correct los path

- src/main/kotlin/no/fdk/fdk_reasoning_service/cache/ReferenceDataCache.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/config/ApplicationURI.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/model/ExternalRDFData.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/ReasoningActivity.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/ReasoningService.kt
- src/main/resources/application.yml
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/Retry.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/utils/DatabaseData.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/utils/ResponseMock.kt
- src/test/resources/data_themes.ttl
- src/test/resources/dataset_0.ttl
- src/test/resources/fdk_ready_datasets.ttl
> feat: add data-themes to theme reasoning

- src/main/kotlin/no/fdk/fdk_reasoning_service/service/InfoModelService.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/ReasoningService.kt
- src/test/resources/infomodel_0.ttl
- src/test/resources/reasoned_infomodels.ttl
glemte at vi bruker temafilter for informasjonsmodeller :sweat_smile:
> fix: add theme-triples for information models

- src/main/kotlin/no/fdk/fdk_reasoning_service/cache/ReferenceDataCache.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/config/ApplicationURI.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/model/ExternalRDFData.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/ConceptService.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/ReasoningActivity.kt
- src/main/resources/application.yml
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/Cache.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/Retry.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/utils/DatabaseData.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/utils/ResponseMock.kt
- src/test/resources/concept_statuses.ttl
- src/test/resources/concepts.ttl
- src/test/resources/reasoned_concepts.ttl
- src/test/resources/saved_concepts.ttl
> feat: add triples for EU concept-statuses

- .github/workflows/deploy-prod&demo.yaml
- .github/workflows/deploy-staging.yaml
- Dockerfile
- deploy/base/deployment-fdk-reasoning-service.yaml
- deploy/base/kustomization.yaml
- deploy/base/service-fdk-reasoning-service.yaml
- deploy/demo/env.yaml
- deploy/demo/kustomization.yaml
- deploy/prod/env.yaml
- deploy/prod/kustomization.yaml
- deploy/staging/env.yaml
- deploy/staging/kustomization.yaml
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/ReasoningService.kt
i hovedsak for å enkelt kunne tukle med minne-verdier i forsøk på å få den til å jobbe seg gjennom geonorge-katalogen, men uansett en forbedring
+en bug kurt stian fant ang. orgPath, det feiler om publisher mangler orgnr og har whitespace elns i navnet
> deploy with kustomize

- pom.xml
- src/main/kotlin/no/fdk/fdk_reasoning_service/cache/ReferenceDataCache.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/config/ApplicationURI.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/model/ExternalRDFData.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/DataServiceService.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/DatasetService.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/ReasoningActivity.kt
- src/main/resources/application.yml
- src/test/kotlin/no/fdk/fdk_reasoning_service/integration/DataServicesIntegration.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/DataServices.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/Retry.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/utils/DatabaseData.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/utils/ResponseMock.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/utils/TestData.kt
- src/test/resources/dataservices.ttl
- src/test/resources/dataset_0.ttl
- src/test/resources/datasets.ttl
- src/test/resources/file_types.ttl
- src/test/resources/media_types.ttl
- src/test/resources/reasoned_dataservices.ttl
- src/test/resources/reasoned_datasets.ttl
- src/test/resources/saved_dataservice_0.ttl
- src/test/resources/saved_dataservices.ttl
- src/test/resources/saved_dataset_0.ttl
- src/test/resources/saved_datasets.ttl
> feat: add iana triple data to datasets and dataservices

- src/main/kotlin/no/fdk/fdk_reasoning_service/cache/ReferenceDataCache.kt
> fix: set org cache to update with 3h interval

- src/main/kotlin/no/fdk/fdk_reasoning_service/cache/ReferenceDataCache.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/config/ApplicationURI.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/model/ExternalRDFData.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/ConceptService.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/DataServiceService.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/DatasetService.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/InfoModelService.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/PublicServiceService.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/ReasoningActivity.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/ThemeUtils.kt
- src/main/resources/application.yml
- src/test/kotlin/no/fdk/fdk_reasoning_service/integration/InformationModelsIntegration.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/DataServices.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/InformationModels.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/Retry.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/utils/DatabaseData.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/utils/ResponseMock.kt
- src/test/resources/datasets.ttl
- src/test/resources/infomodels.ttl
- src/test/resources/linguistic_systems.ttl
- src/test/resources/open_licenses.ttl
- src/test/resources/reasoned_datasets.ttl
- src/test/resources/saved_dataset_0.ttl
- src/test/resources/saved_datasets.ttl
- src/test/resources/saved_infomodel_0.ttl
- src/test/resources/saved_infomodels.ttl
- src/test/resources/saved_public_services.ttl
> linguistic systems and open licenses

- src/main/kotlin/no/fdk/fdk_reasoning_service/cache/ReferenceDataCache.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/config/ApplicationURI.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/model/ExternalRDFData.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/DatasetService.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/InfoModelService.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/ReasoningActivity.kt
- src/main/resources/application.yml
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/Retry.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/utils/DatabaseData.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/utils/ResponseMock.kt
- src/test/resources/datasets.ttl
- src/test/resources/fylker.ttl
- src/test/resources/infomodels.ttl
- src/test/resources/kommuner.ttl
- src/test/resources/nasjoner.ttl
- src/test/resources/reasoned_datasets.ttl
- src/test/resources/reasoned_infomodels.ttl
- src/test/resources/saved_datasets.ttl
- src/test/resources/saved_infomodels.ttl
> feat: add triples from geonorge locations

- src/main/kotlin/no/fdk/fdk_reasoning_service/cache/ReferenceDataCache.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/config/ApplicationURI.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/model/ExternalRDFData.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/DatasetService.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/ReasoningActivity.kt
- src/main/resources/application.yml
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/Cache.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/Retry.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/utils/DatabaseData.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/utils/ResponseMock.kt
- src/test/resources/access_rights.ttl
- src/test/resources/datasets.ttl
- src/test/resources/frequencies.ttl
- src/test/resources/reasoned_datasets.ttl
- src/test/resources/saved_dataset_0.ttl
- src/test/resources/saved_datasets.ttl
> feat: add triples for EU access rights and frequencies

- src/main/kotlin/no/fdk/fdk_reasoning_service/cache/ReferenceDataCache.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/config/ApplicationURI.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/model/ExternalRDFData.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/DatasetService.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/ReasoningActivity.kt
- src/main/resources/application.yml
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/Datasets.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/Retry.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/utils/DatabaseData.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/utils/ResponseMock.kt
- src/test/resources/provenance_statements.ttl
- src/test/resources/saved_dataset_0.ttl
- src/test/resources/saved_dataset_series.ttl
- src/test/resources/saved_datasets.ttl
> feat: add triples for provenance statements

- src/main/kotlin/no/fdk/fdk_reasoning_service/cache/ReferenceDataCache.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/config/ApplicationURI.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/model/ExternalRDFData.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/PublicServiceService.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/ReasoningActivity.kt
- src/main/resources/application.yml
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/PublicServices.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/Retry.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/utils/DatabaseData.kt
- src/test/resources/adms_statuses.ttl
- src/test/resources/public_service_0.ttl
- src/test/resources/public_service_1.ttl
- src/test/resources/publisher_types.ttl
- src/test/resources/reasoned_public_service_0.ttl
- src/test/resources/reasoned_public_service_1.ttl
- src/test/resources/reasoned_public_service_catalog_0.ttl
- src/test/resources/reasoned_public_service_catalog_1.ttl
- src/test/resources/reasoned_public_services.ttl
- src/test/resources/saved_public_service_catalog_0.ttl
- src/test/resources/saved_public_services.ttl
> feat: add triples for adms statuses and publisher types

- src/main/kotlin/no/fdk/fdk_reasoning_service/cache/ReferenceDataCache.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/config/ApplicationURI.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/model/ExternalRDFData.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/PublicServiceService.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/ReasoningActivity.kt
- src/main/resources/application.yml
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/Retry.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/utils/DatabaseData.kt
- src/test/resources/channel_types.ttl
- src/test/resources/evidence_types.ttl
- src/test/resources/public_service_0.ttl
- src/test/resources/public_service_1.ttl
- src/test/resources/reasoned_public_service_0.ttl
- src/test/resources/reasoned_public_service_1.ttl
- src/test/resources/reasoned_public_service_catalog_0.ttl
- src/test/resources/reasoned_public_service_catalog_1.ttl
- src/test/resources/reasoned_public_services.ttl
- src/test/resources/role_types.ttl
- src/test/resources/saved_public_service_catalog_0.ttl
- src/test/resources/saved_public_services.ttl
> feat: add triples for role, channel and evidence types

- src/main/kotlin/no/fdk/fdk_reasoning_service/service/OrganizationService.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/Organization.kt
- src/test/resources/rdf-data/expected/org-data/concept_1_org.ttl
- src/test/resources/rdf-data/input-graphs/concept_1.ttl
> feat: add dct:creator for concept

- pom.xml
- src/main/kotlin/no/fdk/fdk_reasoning_service/cache/ReferenceDataCache.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/config/ApplicationURI.kt
- src/main/kotlin/no/fdk/fdk_reasoning_service/service/ReferenceDataService.kt
- src/main/resources/application.yml
- src/test/kotlin/no/fdk/fdk_reasoning_service/unit/ReferenceData.kt
- src/test/kotlin/no/fdk/fdk_reasoning_service/utils/ResponseMock.kt
- src/test/resources/rdf-data/expected/reference-data/dataset.ttl
- src/test/resources/rdf-data/input-graphs/dataset_extension.ttl
- src/test/resources/rdf-data/reference-data/dataset-types.ttl
> dataset types
